#!/bin/sh

if [ "$1" = '-v' ] || [ "$1" = '--version' ]; then
  echo "$BONPRIX_PACKAGE_VERSION"; exit
fi

usage="$(cat <<EOF
Usage: bonprix admin [commands...]

Description:
  Simplifies administrative activities.

Version: $BONPRIX_PACKAGE_VERSION

Location:
  $BONPRIX_PACKAGE_SOURCES/libexec/admin

Options:
  -?, -h, --help        Show usage (print this text)
  -l, --login           Fully login as admin instead of simulating a login
  -v, --version         Print bonprix CLI version

Commands:
  <no command>          Login as admin
  fix_zsh_comp_perms    Fix Zsh completion permissions
  <any commands>        Execute <commands...> as admin
EOF
)"

if [ "$1" = '-?' ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
  echo "$usage"; exit
fi

unset usage

if [ $# -lt 1 ]; then
  command su - "$(whoami)-admin"
elif [ "$1" = '-l' ] || [ "$1" = '--login' ]; then
  command login "$(whoami)-admin"
elif [ -f "$BONPRIX_PACKAGE_SOURCES/lib/admin/$1.sh" ] \
  && [ -r "$BONPRIX_PACKAGE_SOURCES/lib/admin/$1.sh" ]; then
  filename="$BONPRIX_PACKAGE_SOURCES/lib/admin/$1.sh"; function="$1"; shift

  if [ "$function" = 'fix_zsh_comp_perms' ]; then
    filenames="$1"; shift

    command su "$(whoami)-admin" -c ". '$filename' && $function '$filenames' $*"
  else
    command su "$(whoami)-admin" -c ". '$filename' && $function $*"
  fi
else
  command su "$(whoami)-admin" -c "$*"
fi
