#!/bin/sh

[ "$1" = '-v' ] || [ "$1" = '--version' ]

[ $? -eq 0 ] && echo "$BONPRIX_PACKAGE_VERSION" && exit

usage="$(cat <<EOF
Usage: bonprix admin [commands...]

Description:
  Simplifies administrative activities.

Version: $BONPRIX_PACKAGE_VERSION

Location:
  $BONPRIX_PACKAGE_SOURCES/libexec/admin

Options:
  -?, -h, --help    Show usage (print this text)
  -l, --login       Fully login as admin instead of simulating a login
  -v, --version     Print bonprix CLI version

Commands:
  <no command>      Login as admin
  <any commands>    Execute <commands...> as admin
EOF
)"

[ "$1" = '-?' ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]

[ $? -eq 0 ] && echo "$usage" && exit

if [ $# -lt 1 ]
  then
    command su - "$(whoami)-admin"
elif [ "$1" = '-l' ] || [ "$1" = '--login' ]
  then
    login "$(whoami)-admin"
else
  command su "$(whoami)-admin" -c "$*"
fi
