cask 'java8' unless system '/usr/libexec/java_home --failfast --version 1.8'

brew 'ant'
brew 'graphicsmagick'
brew 'ivy'
brew 'maven'
brew 'nginx'
brew 'tomcat@7'

cask 'docker'
cask 'intellij-idea'
